project:
  type: website

website:
  title: "R4DEV"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kate-chalmers/
      - icon: twitter
        href: https://twitter.com/kategchalmers

format:
  html:
    theme: cosmo
    css: styles.css

editor: source

