project:
  type: website

website:
  title: "Kate Chalmers"
  navbar:
    logo-href: https://kate-chalmers.com/
    right:
      - icon: github
        href: https://github.com/kate-chalmers/
      - icon: twitter
        href: https://twitter.com/kategchalmers

format:
  html:
    theme: cosmo
    css: styles.css

editor: source

comments:
  hypothesis: true

